spring.datasource.url=jdbc:postgresql://localhost:5432/authvault
spring.datasource.username=postgres
spring.datasource.password=Sarika@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
