spring.datasource.url=jdbc:postgresql://localhost:5432/authvault
spring.datasource.username=postgres
spring.datasource.password=Sarika@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.client-id=348698795928-h47r8pkjs5nhkm35so1pdhi8gihe29bv.apps.googleusercontent.com
